server:
  port: 8005
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://25.6.72.47:3306/gateway?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 3
    host: 25.6.72.48
    port: 6379
    password:
    timeout: 3000
    lettuce:
      pool:
        enabled: true
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
logging:
  level:
    com.forward.core.tcpReverseProxy.controller: debug
    com.forward.core.tcpReverseProxy.mapper: debug

mybatis-plus:
  type-aliases-package: com.forward.core.tcpReverseProxy.entity
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

