spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    #    url: jdbc:mysql://25.6.72.40:3306/atmp?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://localhost:3306/gateway?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&serverTimezone=Asia/Shanghai
    username: root
    password: 654321
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

logging:
  level:
    com.forward.core.tcpReverseProxy.controller: debug
    com.forward.core.tcpReverseProxy.mapper: debug

mybatis-plus:
  type-aliases-package: com.forward.core.tcpReverseProxy.entity
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

