server:
  port: 8005
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/gateway?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&serverTimezone=Asia/Shanghai
    username: root
    password: 654321


  redis:
    database: 2
    host: localhost
    port: 6379
    password:
    timeout: 3000
    lettuce:
      pool:
        enabled: true
        max-active: 50
        max-idle: 20
        max-wait: -1
        min-idle: 5

logging:
  level:
    com.forward.core.tcpReverseProxy.controller: debug
    com.forward.core.tcpReverseProxy.mapper: debug

mybatis-plus:
  type-aliases-package: com.forward.core.tcpReverseProxy.entity
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

test:
  ip: 192.168.21.13