spring:
  application:
    name: tcp-proxy
  profiles:
    active: dev

server:
  port: 8005
  servlet:
    context-path: /forward

springdoc:
  packagesToScan:
    - com.forward.core.tcpReverseProxy
  pathsToMatch:
    - /**
  swagger-ui:
    path: /swagger-ui.html
  show-actuator: true