server:
  port: 8006
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:mem:gateway;DB_CLOSE_DELAY=-1;MODE=MySQL # mem指定数据库使用内存模式 MODE指定使用MySQL模式
    driver-class-name: org.h2.Driver
    username: root
    password: ENC(jn6Y8mdMrlON84fLrNihfQ==)
  sql:
    init:
      schema-locations: classpath:h2/schema.sql
      data-locations: classpath:h2/local-data.sql
  h2:
    console:
      enabled: true # 访问h2数据库控制台



  redis:
    database: 2
    host: localhost
    port: 6379
    timeout: 3000
    lettuce:
      pool:
        enabled: true
        max-active: 50
        max-idle: 20
        max-wait: 100
        min-idle: 5
logging:
  level:
    com.forward.core.tcpReverseProxy.controller: debug
    com.forward.core.tcpReverseProxy.mapper: debug

